# Generated by Django 4.0.2 on 2022-02-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='Post',
        ),
    ]
